//===---- include/gcinfo/gcinfo.h -------------------------------*- C++ -*-===//
//
// LLILC
//
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// \brief GCInfo Generator for LLILC
///
//===----------------------------------------------------------------------===//

#ifndef GCINFO_H
#define GCINFO_H

#include "gcinfoencoder.h"
#include "jitpch.h"
#include "LLILCJit.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/IR/ValueMap.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include <sstream>

class GcInfoAllocator;
class GcInfoEncoder;

/// \brief Per Function GcInfo
// This Data-structure records the frame-offsets for certain special
// allocations in each function generated by LLILC. This includes:
//  -> Special Symbols: GsCookie, SecurityObject, GenericsContext
//                      which must be identified to the runtime.
//  -> Pinned pointers: Whose location must be reported to the runtime.
//                      Pinned pointers are reported as untracked
//  -> GC Aggregates:   Location of all GC-aggregates allocated on
//                      the stack, also reported as untracked.
//
// The stackmap generated via Statepoints only handles SSA values,
// and therefore does not track pointers contained within GC-aggregates.
// To circumvent this problem, we report all pointers within
// GC-aggregates as untracked. The Gc-aggregate stack allocations are
// known to be live throughout the function, because the reader marks
// them as frame-escaped.

class GcFuncInfo {
public:
  GcFuncInfo(const llvm::Function *F);

  void recordPinnedSlot(llvm::AllocaInst *Alloca);
  void recordGcAggregate(llvm::AllocaInst *Alloca);
  void getEscapingLocations(llvm::SmallVector<llvm::Value *, 4> &EscapingLocs);

  // Function for which GcInfo is recorded
  const llvm::Function *Function;

  // Allocation to frame-offset Mappings
  llvm::ValueMap<const llvm::AllocaInst *, int32_t> PinnedSlots;
  llvm::ValueMap<const llvm::AllocaInst *, int32_t> GcAggregates;
  llvm::AllocaInst *GsCookie;
  int32_t GsCookieOffset;
  uint32_t GsCkValidRangeStart;
  uint32_t GsCkValidRangeEnd;
  llvm::AllocaInst *SecurityObject;
  int32_t SecurityObjectOffset;
  llvm::AllocaInst *GenericsContext;
  int32_t GenericsContextOffset;
  GENERIC_CONTEXTPARAM_TYPE GenericsContextParamType;
};

/// \brief Per Module / Jit Invocation GcInfo
// GcFuncInfo Map for all functions in a Module.

class GcInfo {
public:
  static const uint32_t UnmanagedAddressSpace = 0;
  static const uint32_t ManagedAddressSpace = 1;
  static const int32_t InvalidPointerOffset = -1;

  static bool isGcPointer(const llvm::Type *Type);
  static bool isGcAggregate(const llvm::Type *Type);
  static bool isGcType(const llvm::Type *Type) {
    return isGcPointer(Type) || isGcAggregate(Type);
  }
  static bool isUnmanagedPointer(const llvm::Type *Type) {
    return Type->isPointerTy() && !isGcPointer(Type);
  }
  static bool isGcFunction(const llvm::Function *F);
  static bool isFPBasedFunction(const llvm::Function *F);

  static void getGcPointers(llvm::StructType *StructTy,
                            const llvm::DataLayout &DataLayout,
                            llvm::SmallVector<uint32_t, 4> &GcPtrOffsets);

  GcFuncInfo *newGcInfo(const llvm::Function *F);
  GcFuncInfo *getGcInfo(const llvm::Function *F);

  llvm::ValueMap<const llvm::Function *, GcFuncInfo *> GcInfoMap;
};

/// \brief This is the translator from LLVM's GC StackMaps
///  to CoreCLR's GcInfo encoding.
class GcInfoEmitter {
public:
  /// Construct a GCInfo object
  /// \param JitCtx Context record for the method's jit request.
  /// \param StackMapData A pointer to the .llvm_stackmaps section
  ///        loaded in memory
  /// \param Allocator The allocator to be used by GcInfo encoder
  /// \param OffsetCorrection FunctionStart - CodeBlockStart difference
  GcInfoEmitter(LLILCJitContext *JitCtx, uint8_t *StackMapData,
                GcInfoAllocator *Allocator, size_t OffsetCorrection);

  /// Emit GC Info to the EE using GcInfoEncoder.
  void emitGCInfo();

  /// Destructor -- delete allocated memory
  ~GcInfoEmitter();

private:
  void emitGCInfo(const GcFuncInfo *GcFuncInfo);
  void encodeHeader(const GcFuncInfo *GcFuncInfo);
  void encodeTrackedPointers(const GcFuncInfo *GcFuncInfo);
  void encodePinnedPointers(const GcFuncInfo *GcFuncInfo);
  void encodeSpecialSlots(const GcFuncInfo *GcFuncInfo);
  void encodeGcAggregates(const GcFuncInfo *GcFuncInfo);
  void finalizeEncoding();
  void emitEncoding();

  bool needsGCInfo(const llvm::Function *F);
  bool needsPointerReporting(const llvm::Function *F);

  bool isTrackedSlot(GcSlotId SlotID);
  GcSlotId getSlot(int32_t Offset, GcSlotFlags Flags);
  GcSlotId getTrackedSlot(int32_t Offset);
  GcSlotId getAggregateSlot(int32_t Offset);
  GcSlotId getPinnedSlot(int32_t Offset);

  const LLILCJitContext *JitContext;
  const uint8_t *LLVMStackMapData;
  GcInfoEncoder Encoder;

  // The InstructionOffsets reported at Call-sites are with respect to:
  // (1) FunctionEntry in LLVM's StackMap
  // (2) CodeBlockStart in CoreCLR's GcTable
  // OffsetCorrection accounts for the difference:
  // FunctionStart - CodeBlockStart
  //
  // There is typically a difference between the two even in the JIT case
  // (where we emit one function per module) because of some additional
  // code like the gc.statepoint_poll() method.
  size_t OffsetCorrection;

  // Offset to SlotID Map
  // Currently, the base pointer for all slots is the current function's SP.
  // If this changes, we need to change SlotMap
  //   from {Offset -> SlotID} mapping
  //   to {(base, offset) -> SlotID) mapping.

  llvm::DenseMap<int32_t, uint32_t> SlotMap;
  GcSlotId FirstTrackedSlot;
  size_t NumTrackedSlots;

#if !defined(NDEBUG)
  bool EmitLogs;
  std::ostringstream SlotStream;
  std::ostringstream LiveStream;
#endif // !NDEBUG

#if defined(PARTIALLY_INTERRUPTIBLE_GC_SUPPORTED)
  size_t NumCallSites;
  unsigned *CallSites;
  BYTE *CallSiteSizes;
#endif // defined(PARTIALLY_INTERRUPTIBLE_GC_SUPPORTED)
};

/// \brief MachineFunctionPass to record frame information
/// for special allocations in GcFuncInfo
class GcInfoRecorder : public llvm::MachineFunctionPass {
public:
  explicit GcInfoRecorder(bool TrackGcAggrs) : MachineFunctionPass(ID) {
    TrackGcAggregates = TrackGcAggrs;
  }
  bool runOnMachineFunction(llvm::MachineFunction &MF) override;

private:
  static char ID;
  bool TrackGcAggregates;
};

#endif // GCINFO_H
